#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

if [[ -f "${DIR}/libsslkeylog.so" ]]; then
    export LD_PRELOAD="${DIR}/libsslkeylog.so"
else
    export LD_PRELOAD="${DIR}/../share/sslkeylog/preload/libsslkeylog.so"
fi


if [[ -z $SSLKEYLOGFILE ]]; then
    SSLKEYLOGFILE=$(mktemp -t "sslkeys-XXXXXXXX.txt")
    echo "*** SSLKEYLOGFILE set to ${SSLKEYLOGFILE} ***"
fi

export SSLKEYLOGFILE

exec "$@"
