#!/bin/bash

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

if [[ -f "${DIR}/libsslkeylog.so" ]]; then
    export LD_PRELOAD="${DIR}/libsslkeylog.so"
else
    export LD_PRELOAD="${DIR}/../share/sslkeylog/preload/libsslkeylog.so"
fi


if [[ -z $SSLKEYLOGFILE && -z $HOOKED_SSLKEYLOGFILE ]]; then
    HOOKED_SSLKEYLOGFILE=$(mktemp -u -t "sslkeylogged-XXXXXXXX.keys")
    echo "*** HOOKED_SSLKEYLOGFILE set to ${HOOKED_SSLKEYLOGFILE} ***"
fi

export HOOKED_SSLKEYLOGFILE

exec "$@"
